### ISSUE TITLE
[Question] Sharing music library

### ISSUE THREAD

**Issue by JoseBarakat** [dessalines/torrenttunes-client#98]
Hi. I have a large collection of properly tagged music that I want to share, encoded in Opus (from Flac) at 512 kbps like this:
`$ opusenc --bitrate 512 --max-delay 10 inputName.flac outputName.opus`

1. Will TorrentTunes support this audio format? 
2. Is it necessary to always create/open a torrent file with the album or could be a public folder in Mega (http://mega.nz) or similar services a viable option(s)?

**Comment by dessalines** [comment]
Unfortunately torrenttunes doesn't currently support flac, mainly because browsers can't handle it easily yet. 

The torrent files are on a per song/recording basis, to keep things highly normalized. The torrentTunes scanner creates torrent files out of the well-tagged songs already in your library.

**Comment by JoseBarakat** [comment]
@dessalines Ok, sorry to hear that 'cause I like very much the Opus encoder technology (but I'll wait).
I'm going to try that. 

By the way, still trying to load TorrentTunes for the first time. I have Ubuntu 16.10 and have just installed Java JDK 8 from ["Oracle Java (JDK) 7 / 8 / 9 Installer PPA"](https://launchpad.net/~webupd8team/+archive/ubuntu/java) in a recent Ubuntu installation (less than 15 days), and I'm having this issue:

```
$ java -jar torrenttunes-launcher.jar
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at com.torrenttunes.launcher.tools.Updater.checkForUpdate(Updater.java:33)
	at com.torrenttunes.launcher.Main.doMain(Main.java:52)
	at com.torrenttunes.launcher.Main.main(Main.java:123)
```

![captura de pantalla de 2016-11-30 22-57-24](https://cloud.githubusercontent.com/assets/15618933/20781390/662a3e28-b750-11e6-8fd0-c8c7e5c14189.png)


I have waited 15min but it doesn't update/load.

**Comment by dessalines** [comment]
Sorry about that, I changed my github username and it broke some things. 

[Here's](https://github.com/dessalines/torrenttunes-launcher/releases/download/1.0.1/torrenttunes-launcher.jar) the fixed launcher jar.

**Comment by JoseBarakat** [comment]
Great! It's running fine on Firefox 50.0
![captura de pantalla_2016-12-01_17-46-30](https://cloud.githubusercontent.com/assets/15618933/20815982/26682a40-b7ee-11e6-9d02-5bae350fa654.png)

But, someday I'll have to turn my laptop off. For how many time should I have to seed my collection before turning off my machine? And, are you going to support Opus in a near future?

Thanks!
